-- GENERATED by supabase/tests/scripts/generate-seed.ts from @nystart/core. Do not edit by hand.
-- Run: pnpm --filter @nystart/db-tests seed:generate

insert into public.substance_types (id, category, featured, sort_order, medically_supervised_withdrawal_advised, overdose_risk_after_break, acute_stimulant_risk, milestone_thresholds_hours, education_status) values
  ('crack_cocaine', 'stimulant', true, 1, false, false, true, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'draft_pending_clinical_review'),
  ('powder_cocaine', 'stimulant', true, 2, false, false, true, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'draft_pending_clinical_review'),
  ('amphetamine', 'stimulant', false, 3, false, false, true, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('methamphetamine', 'stimulant', false, 4, false, false, true, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('cannabis', 'cannabis', false, 5, false, false, false, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('heroin', 'opioid', false, 6, false, true, false, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('other_opioids', 'opioid', false, 7, false, true, false, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('prescription_opioids', 'opioid', false, 8, false, true, false, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('benzodiazepines', 'depressant', false, 9, true, false, false, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('alcohol', 'depressant', false, 10, true, false, false, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('mdma', 'entactogen', false, 11, false, false, false, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned'),
  ('other', 'other', false, 12, false, false, false, array[24, 48, 72, 168, 336, 720, 1440, 2160, 4320, 8760], 'planned')
on conflict (id) do update set category = excluded.category, featured = excluded.featured, sort_order = excluded.sort_order,
  medically_supervised_withdrawal_advised = excluded.medically_supervised_withdrawal_advised,
  overdose_risk_after_break = excluded.overdose_risk_after_break, acute_stimulant_risk = excluded.acute_stimulant_risk,
  milestone_thresholds_hours = excluded.milestone_thresholds_hours, education_status = excluded.education_status;

insert into public.achievements (id, kind, threshold_hours, sort_order) values
  ('time_24h', 'time', 24, 0),
  ('time_48h', 'time', 48, 1),
  ('time_72h', 'time', 72, 2),
  ('time_168h', 'time', 168, 3),
  ('time_336h', 'time', 336, 4),
  ('time_720h', 'time', 720, 5),
  ('time_1440h', 'time', 1440, 6),
  ('time_2160h', 'time', 2160, 7),
  ('time_4320h', 'time', 4320, 8),
  ('time_8760h', 'time', 8760, 9),
  ('first_checkin', 'activity', null, 100),
  ('seven_checkins', 'activity', null, 101),
  ('first_craving_exercise', 'activity', null, 102),
  ('first_savings_goal', 'activity', null, 103),
  ('trusted_contact_saved', 'activity', null, 104),
  ('first_plan_step', 'activity', null, 105),
  ('first_journal_entry', 'activity', null, 106),
  ('weekly_goal_reached', 'activity', null, 107)
on conflict (id) do update set kind = excluded.kind, threshold_hours = excluded.threshold_hours, sort_order = excluded.sort_order;

insert into public.support_resources (id, name, category, description, phone, website, chat_url, hours, coverage, eligibility, source_url, verified_on, verification) values
  ('ambulanse-113', 'Medisinsk nødtelefon 113', 'emergency', 'Ring 113 ved livsfare, akutt alvorlig sykdom eller skade – for eksempel brystsmerter, kramper, bevisstløshet eller mistanke om overdose.', '113', null, null, 'Døgnåpen', 'Hele landet', null, 'https://www.helsedirektoratet.no/veiledere/legevakt-og-legevaktsentral/telefoni-og-nodnett', '2026-10-08', 'search_extract'),
  ('legevakt-116117', 'Legevakt 116 117', 'urgent_medical', 'Når du trenger lege raskt, men det ikke er livstruende og fastlegen ikke er tilgjengelig. Du blir satt over til nærmeste legevakt.', '116 117', null, null, 'Døgnåpen', 'Hele landet', 'Alle som oppholder seg i Norge, også de uten fastlege', 'https://www.helsenorge.no/en/foreigners-in-norway/refugees-and-asylum-seekers/where-to-get-help/', '2026-10-08', 'search_extract'),
  ('politi-112', 'Politiets nødtelefon 112', 'emergency', 'Når det haster og liv, helse eller sikkerhet er truet av andre.', '112', null, null, 'Døgnåpen', 'Hele landet', null, 'https://www.helsedirektoratet.no/veiledere/legevakt-og-legevaktsentral/telefoni-og-nodnett', '2026-10-08', 'search_extract'),
  ('giftinformasjonen', 'Giftinformasjonen', 'drug_information', 'Råd på telefon hvis noen kan ha fått i seg noe giftig, også rusmidler eller for mye av et legemiddel. Ved alvorlige symptomer: ring 113.', '22 59 13 00', 'https://www.helsenorge.no/giftinformasjon/', null, 'Døgnåpen', 'Hele landet', null, 'https://www.helsenorge.no/giftinformasjon/rusmidler/', '2026-10-08', 'search_extract'),
  ('mental-helse-hjelpetelefonen', 'Mental Helse Hjelpetelefonen', 'crisis_line', 'Gratis telefon for alle som trenger noen å snakke med. Du kan være anonym.', '116 123', 'https://mentalhelse.no/fa-hjelp/hjelpetelefonen/', null, 'Døgnåpen', 'Hele landet', null, 'https://mentalhelse.no/fa-hjelp/hjelpetelefonen/', '2026-10-08', 'search_extract'),
  ('kirkens-sos', 'Kirkens SOS', 'crisis_line', 'Krisetelefon der du kan snakke anonymt når livet er vanskelig, også om selvmordstanker. Har også skriftlige tjenester.', '22 40 00 40', 'https://www.kirkens-sos.no/', 'https://soschat.no', 'Telefon: døgnåpen. Chat: begrensede åpningstider.', 'Hele landet', null, 'https://www.kirkens-sos.no/telefon', '2026-10-08', 'search_extract'),
  ('rusinfo', 'RUSinfo', 'drug_information', 'Anonym og gratis informasjonstjeneste om alkohol, narkotika og pengespill – på telefon eller chat. Ikke en nødtjeneste.', '915 08 588', 'https://rusinfo.no/', null, 'Hverdager kl. 11–18 (stengt 14.30–15). Stengt i helgene.', 'Hele landet', 'Alle, også pårørende', 'https://rusinfo.no/om-rustelefonen/', '2026-10-08', 'search_extract'),
  ('helsenorge-hjelp-med-rusproblemer', 'Helsenorge – hjelp med rusproblemer', 'treatment_access', 'Slik får du hjelp via fastlegen eller kommunens rustjeneste, og hvordan henvisning til spesialisert rusbehandling (TSB) fungerer.', null, 'https://www.helsenorge.no/rus-og-avhengighet/hjelp-med-rusproblemer/', null, null, 'Hele landet', 'Kommunale tjenester krever ikke at du er rusfri', 'https://www.helsenorge.no/rus-og-avhengighet/hjelp-med-rusproblemer/', '2026-10-08', 'search_extract'),
  ('helsenorge-velg-behandlingssted', 'Velg behandlingssted', 'treatment_access', 'Offentlig oversikt over behandlingssteder og ventetider, også for rus- og avhengighetsbehandling.', null, 'https://tjenester.helsenorge.no/velg-behandlingssted/behandlingssteder', null, null, 'Hele landet', null, 'https://tjenester.helsenorge.no/velg-behandlingssted/behandlingssteder', '2026-10-08', 'search_extract'),
  ('anonyme-narkomane-norge', 'Anonyme Narkomane (NA) Norge', 'peer_support', 'Selvhjelpsfellesskap for folk som vil slutte med rusmidler. Møter over hele landet, uten påmelding.', '905 29 359', 'https://nanorge.org/', null, 'Kontakttelefon alle dager kl. 10–22', 'Hele landet', null, 'https://nanorge.org/kontakt/', '2026-10-08', 'search_extract'),
  ('anonyme-alkoholikere-norge', 'Anonyme Alkoholikere (AA) Norge', 'peer_support', 'Selvhjelpsfellesskap for folk som vil slutte å drikke. Kontakttelefonen kan sette deg i kontakt med et medlem der du bor.', '911 77 770', 'https://www.anonymealkoholikere.no/', null, 'Hverdager kl. 11–15 og alle dager kl. 18–22', 'Hele landet', null, 'https://www.anonymealkoholikere.no/2/kontakt/', '2026-10-08', 'search_extract'),
  ('nalokson-overdoseforebygging', 'Forebygging av overdose (nalokson)', 'harm_reduction', 'Nalokson nesespray kan midlertidig reversere en opioidoverdose mens du venter på ambulanse. Helsenorge forklarer hvordan overdose kan forebygges.', null, 'https://www.helsenorge.no/rus-og-avhengighet/forebygging-av-overdose', null, null, 'Hele landet', null, 'https://www.helsenorge.no/rus-og-avhengighet/forebygging-av-overdose', '2026-10-08', 'search_extract'),
  ('nalokson-utdelingssteder', 'Naloksonprosjektet – utdelingssteder', 'harm_reduction', 'Kart over steder som deler ut nalokson nesespray med kort opplæring.', null, 'https://www.nalokson.uio.no/', null, null, 'Hele landet', 'Personer i risiko for opioidoverdose, pårørende og andre som kan komme til å se en overdose', 'https://www.nalokson.uio.no/nalokson/', '2026-10-08', 'search_extract'),
  ('ivareta-parorendetelefonen', 'Ivareta – Pårørendetelefonen', 'relatives', 'Gratis og anonym telefon for alle som er berørt av andres rusbruk. De som svarer er selv pårørende.', '800 40 567', 'https://www.ivareta.no/', null, 'Hverdager kl. 9–15, tirsdag også kl. 18–21', 'Hele landet', 'Pårørende og etterlatte', 'https://www.ivareta.no/deg-som-parorende/parorendetelefonen/', '2026-10-08', 'search_extract'),
  ('alarmtelefonen-116111', 'Alarmtelefonen for barn og unge', 'crisis_line', 'Gratis hjelpetelefon for barn og unge som opplever vold, overgrep eller omsorgssvikt – også når foreldre ruser seg.', '116 111', 'https://www.116111.no/', null, 'Telefon: døgnåpen', 'Hele landet', 'Barn og unge, og voksne som er bekymret for et barn', 'https://www.116111.no/omalarmtelefonen', '2026-10-08', 'search_extract'),
  ('rio', 'Rusmisbrukernes interesseorganisasjon (RIO)', 'user_organisation', 'Bruker- og interesseorganisasjon for folk med erfaring fra rusavhengighet og rusbehandling.', null, 'https://rio.no/', null, null, 'Hele landet', null, 'https://rio.no/personvern/', '2026-10-08', 'search_extract'),
  ('prolar-nett', 'proLAR Nett', 'user_organisation', 'Nasjonalt forbund for folk i legemiddelassistert rehabilitering (LAR).', null, 'https://prolar.no/', null, null, 'Hele landet', 'Personer i LAR', 'https://prolar.no/prosjekter-1/hepatitt-c', '2026-10-08', 'search_extract')
on conflict (id) do update set name = excluded.name, category = excluded.category, description = excluded.description,
  phone = excluded.phone, website = excluded.website, chat_url = excluded.chat_url, hours = excluded.hours,
  coverage = excluded.coverage, eligibility = excluded.eligibility, source_url = excluded.source_url,
  verified_on = excluded.verified_on, verification = excluded.verification;
