/**
 * Builds supabase/seed.sql from the canonical catalogues in @nystart/core, so
 * the bundled offline copy and the database never drift apart.
 */
import { ACTIVITY_ACHIEVEMENTS, HOUR_MS, SUBSTANCES, SUPPORT_RESOURCES } from "@nystart/core";

function lit(v: string | number | boolean | undefined | null): string {
  if (v === undefined || v === null) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
}

export function buildSeedSql(): string {
  const lines: string[] = [
    "-- GENERATED by supabase/tests/scripts/generate-seed.ts from @nystart/core. Do not edit by hand.",
    "-- Run: pnpm --filter @nystart/db-tests seed:generate",
    "",
    "insert into public.substance_types (id, category, featured, sort_order, medically_supervised_withdrawal_advised, overdose_risk_after_break, acute_stimulant_risk, milestone_thresholds_hours, education_status) values",
    SUBSTANCES.map(
      (s) =>
        `  (${lit(s.id)}, ${lit(s.category)}, ${s.featured}, ${s.order}, ${s.safety.medicallySupervisedWithdrawalAdvised}, ${s.safety.overdoseRiskAfterBreak}, ${s.safety.acuteStimulantRisk}, array[${s.milestoneThresholdsMs.map((ms) => ms / HOUR_MS).join(", ")}], ${lit(s.educationStatus)})`,
    ).join(",\n"),
    "on conflict (id) do update set category = excluded.category, featured = excluded.featured, sort_order = excluded.sort_order,",
    "  medically_supervised_withdrawal_advised = excluded.medically_supervised_withdrawal_advised,",
    "  overdose_risk_after_break = excluded.overdose_risk_after_break, acute_stimulant_risk = excluded.acute_stimulant_risk,",
    "  milestone_thresholds_hours = excluded.milestone_thresholds_hours, education_status = excluded.education_status;",
    "",
  ];

  const thresholds = SUBSTANCES[0]!.milestoneThresholdsMs.map((ms) => ms / HOUR_MS);
  const achievementRows = [
    ...thresholds.map((h, i) => `  (${lit(`time_${h}h`)}, 'time', ${h}, ${i})`),
    ...ACTIVITY_ACHIEVEMENTS.map((id, i) => `  (${lit(id)}, 'activity', null, ${100 + i})`),
  ];
  lines.push(
    "insert into public.achievements (id, kind, threshold_hours, sort_order) values",
    achievementRows.join(",\n"),
    "on conflict (id) do update set kind = excluded.kind, threshold_hours = excluded.threshold_hours, sort_order = excluded.sort_order;",
    "",
    "insert into public.support_resources (id, name, category, description, phone, website, chat_url, hours, coverage, eligibility, source_url, verified_on, verification) values",
    SUPPORT_RESOURCES.map(
      (r) =>
        `  (${lit(r.id)}, ${lit(r.name)}, ${lit(r.category)}, ${lit(r.description)}, ${lit(r.phone)}, ${lit(r.website)}, ${lit(r.chatUrl)}, ${lit(r.hours)}, ${lit(r.coverage)}, ${lit(r.eligibility)}, ${lit(r.sourceUrl)}, ${lit(r.verifiedOn)}, ${lit(r.verification)})`,
    ).join(",\n"),
    "on conflict (id) do update set name = excluded.name, category = excluded.category, description = excluded.description,",
    "  phone = excluded.phone, website = excluded.website, chat_url = excluded.chat_url, hours = excluded.hours,",
    "  coverage = excluded.coverage, eligibility = excluded.eligibility, source_url = excluded.source_url,",
    "  verified_on = excluded.verified_on, verification = excluded.verification;",
    "",
  );
  return lines.join("\n");
}
